[build]
  base = "frontend-user"
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions" # Pastikan ini menunjuk ke folder yang namanya BENAR

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200