[build]
  base = "frontend-user"
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat" # Ini akan mengarahkan /api/X ke /.netlify/functions/api/X
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200